### ISSUE TITLE
Is this still a thing?

### ISSUE THREAD

**Issue by wallymathieu** [frank-fs/frank#49]
How does this lib compare to the other f# web combinator libs?

**Comment by panesofglass** [comment]
I would suggest you try another option. I haven't been actively maintaining this for some time, and I've not heard much interest from others in using it. The benefits for frank are 1) it is small, 2) it can be used as a source file dependency, 3) it uses `System.Net.Http` types rather than a custom set of types. I had intended to turn this into a combinator library for use with Azure Functions, but I'm not sure how much that's needed.

**Comment by panesofglass** [comment]
Making updates in #51, so this is once again a thing. :)

**Comment by panesofglass** [comment]
Just released 4.0.0: https://www.nuget.org/packages/Frank/4.0.0
